### PR TITLE
Add support for more cachable file types in CacheManifestLinker

### PR DESCRIPTION
**Pull request by xylo**
At the moment only a small set of hard coded file types (mostly image types) are cached through the cache manifest generated by CacheManifestLinker.

This patch
- extends the supported file types by the popular vector graphics format "svg",
- adds a configuration property "touchkit.manifestlinker.additionalCacheFileExtension" for widgetset configuration files to allow users to extends the list of cached file types and 
- adds the asciidoc documentation for the new property

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/touchkit/1)

### CODE REVIEW

**Comment by johannesh2** [comment]
Sorry for keeping this PR open so long. I'm closing this, because we stopped supporting TouchKit earlier this year. The version this PR is basing on doesn't get new releases anymore and this PR has conflicts with master, which is the Apache 2.0 licensed FW8 version. I recommend doing a PR to https://github.com/parttio/touchkit with a lot higher hopes of getting it merged. Again, sorry for the inconvenience.

**Comment by xylo** [comment]
Thanks for the info.  However, the development of https://github.com/parttio/touchkit seems to got also stuck (no reaction on my question about the [Future of touchkit / vaadin mobile development]( https://github.com/parttio/touchkit/issues/7).  Seems that nobody knows if vaadin has any future regarding mobile web development.  Looks like it's not a good choice anymore if you plan to support mobile devices. :(  That's a pitty.

**Comment by Peppe** [comment]
Hi! The web has done great leaps forward during the years since we originally introduced TouchKit. Apps can be built more easily responsively now than it was possible back then. Another problem with TouchKit is that is has a second set of components that feel outdated today, to say the least.

A strong showcase on how to do mobile with Vaadin is our [Bakery App Starter](https://vaadin.com/docs/v8/bakeryfw8/overview.html) which was released around the same time that TouchKit development was moved to /parttio/. Check out [the demo](https://bakery.demo.vaadin.com/) which works beautifully on desktop, tablet and mobile. The app uses regular Vaadin components, but the views are designed mobile first and scaled up with standard CSS media queries.

Taking this even further, we released this week a sneak peak on Vaadin 10 (developer preview) along with the same Bakery app written for that version. [Demo here](https://bakery-flow.demo.vaadin.com). It not only have the views designed for mobile, but also comes with a completely new set of Vaadin components with are all designed to be modern and touch friendly. As it is only a preview so far, some of the Java APIs are still missing and today you have to use client based solutions to use some components, but we are getting there. By the end of the year it should be quite stable.

I encourage you to have a look at the app embrace the matured browser platform to build your mobile views.

**Comment by xylo** [comment]
@Peppe: Thanks a lot for the clarification.  It's good to hear that vaadin did not drop the support for mobile devices.  Maybe this information should be also placed on a prominent vaadin web page, since it's really hard to find something about it on the web.  Just try to google for "vaadin mobile development".  You will mainly find outdated information regarding vaadin 7 and touchkit but no hint at all how mobile web development can be done with Vaadin 8 or 10.  At least I didn't find it.  But now I have a starting point.  Thanks!

**Comment by Peppe** [comment]
Great! Thanks for the feedback. I will see what we can do to get the word out better.

**Pull request closed without merging**
